db:
  host: 'localhost' #'legendhallofalcohol.caeegmvfe5w3.ap-northeast-2.rds.amazonaws.com'
  username: 'postgres'
  password: 'bluesun' #'benjamin987'
  synchronize: true

jwt:
  secret: 'Secret1234'
